# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Иван/Desktop/123/shifr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shifr(object):
    def setupUi(self, Shifr):
        Shifr.setObjectName("Shifr")
        Shifr.resize(476, 361)
        font = QtGui.QFont()
        font.setPointSize(10)
        Shifr.setFont(font)
        self.label = QtWidgets.QLabel(Shifr)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ImageLineEdit = QtWidgets.QLineEdit(Shifr)
        self.ImageLineEdit.setGeometry(QtCore.QRect(10, 50, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ImageLineEdit.setFont(font)
        self.ImageLineEdit.setText("")
        self.ImageLineEdit.setObjectName("ImageLineEdit")
        self.ImageButton = QtWidgets.QPushButton(Shifr)
        self.ImageButton.setGeometry(QtCore.QRect(370, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImageButton.setFont(font)
        self.ImageButton.setObjectName("ImageButton")
        self.radioButton1 = QtWidgets.QRadioButton(Shifr)
        self.radioButton1.setGeometry(QtCore.QRect(10, 100, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton1.setFont(font)
        self.radioButton1.setChecked(True)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(Shifr)
        self.radioButton2.setGeometry(QtCore.QRect(10, 170, 301, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton2.setFont(font)
        self.radioButton2.setObjectName("radioButton2")
        self.CodeLineEdit = QtWidgets.QLineEdit(Shifr)
        self.CodeLineEdit.setGeometry(QtCore.QRect(10, 130, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CodeLineEdit.setFont(font)
        self.CodeLineEdit.setText("")
        self.CodeLineEdit.setObjectName("CodeLineEdit")
        self.RarLineEdit = QtWidgets.QLineEdit(Shifr)
        self.RarLineEdit.setEnabled(False)
        self.RarLineEdit.setGeometry(QtCore.QRect(10, 200, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RarLineEdit.setFont(font)
        self.RarLineEdit.setText("")
        self.RarLineEdit.setObjectName("RarLineEdit")
        self.RarButton = QtWidgets.QPushButton(Shifr)
        self.RarButton.setEnabled(False)
        self.RarButton.setGeometry(QtCore.QRect(370, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RarButton.setFont(font)
        self.RarButton.setObjectName("RarButton")
        self.DoneButton = QtWidgets.QPushButton(Shifr)
        self.DoneButton.setGeometry(QtCore.QRect(364, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DoneButton.setFont(font)
        self.DoneButton.setObjectName("DoneButton")
        self.RarLineEditName = QtWidgets.QLineEdit(Shifr)
        self.RarLineEditName.setEnabled(False)
        self.RarLineEditName.setGeometry(QtCore.QRect(10, 270, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RarLineEditName.setFont(font)
        self.RarLineEditName.setText("")
        self.RarLineEditName.setObjectName("RarLineEditName")
        self.labelName = QtWidgets.QLabel(Shifr)
        self.labelName.setEnabled(False)
        self.labelName.setGeometry(QtCore.QRect(10, 240, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")

        self.retranslateUi(Shifr)
        QtCore.QMetaObject.connectSlotsByName(Shifr)

    def retranslateUi(self, Shifr):
        _translate = QtCore.QCoreApplication.translate
        Shifr.setWindowTitle(_translate("Shifr", "Form"))
        self.label.setText(_translate("Shifr", "Изображение"))
        self.ImageButton.setText(_translate("Shifr", "Выбрать"))
        self.radioButton1.setText(_translate("Shifr", "Текст в код"))
        self.radioButton2.setText(_translate("Shifr", "Архив в изображение (.rar)"))
        self.RarButton.setText(_translate("Shifr", "Выбрать"))
        self.DoneButton.setText(_translate("Shifr", "Старт"))
        self.labelName.setText(_translate("Shifr", "Конечное название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Shifr = QtWidgets.QWidget()
    ui = Ui_Shifr()
    ui.setupUi(Shifr)
    Shifr.show()
    sys.exit(app.exec_())
